title: Loredana Salutari
description: >-
  IT professional and certified coach with a focus on professional change,
  career transitions, and identity in organizational environments.
lang: en
url: "https://loredanasalutari.github.io"
baseurl: "/coaching"
theme: jekyll-theme-minimal
markdown: GFM
show_downloads: false

exclude:
  - README.md
